/**
 * @module constants
 *
 * Static type definitions and data dictionaries for the Grailguard tower-defense
 * engine. Defines the full set of unit types, building types, factions, game
 * phases, spells, and enemy affixes, together with their numerical stats used
 * by the simulation in {@link GameEngine}.
 */

/**
 * Which side of the conflict an entity belongs to.
 * - `'ally'` -- player-controlled defenders
 * - `'enemy'` -- wave-spawned attackers
 */
export type Faction = 'ally' | 'enemy';

/**
 * The three high-level phases a game session cycles through.
 * - `'build'`     -- player places and upgrades structures
 * - `'defend'`    -- enemies spawn and advance toward the sanctuary
 * - `'game_over'` -- terminal state after victory or defeat
 */
export type GamePhase = 'build' | 'defend' | 'game_over';

/**
 * Identifiers for the castable spells available to the player.
 * Each spell has a faith cost and cooldown managed in {@link GameEngine}.
 */
export type SpellType =
  | 'smite'
  | 'holy_nova'
  | 'zealous_haste'
  | 'earthquake'
  | 'chrono_shift'
  | 'meteor_strike'
  | 'divine_shield';

/**
 * Modifiers that can be applied to enemy units starting at wave 6.
 * - `'armored'`       -- takes 50% reduced non-magic damage
 * - `'swift'`         -- doubled movement speed and halved attack speed
 * - `'regenerating'`  -- passively regenerates HP over time
 * - `'ranged'`        -- gains a 15-range ranged attack
 * - `'vampiric'`      -- heals for 50% of damage dealt
 * - `'explosive'`     -- deals AoE damage to nearby allies on death
 */
export type EnemyAffix = 'armored' | 'swift' | 'regenerating' | 'ranged' | 'vampiric' | 'explosive';

/**
 * All unit archetypes in the game. Ally units (`wall` through `knight`) are
 * spawned by buildings, while enemy units (`goblin` through `boss`) are
 * generated by the wave system.
 */
export type UnitType =
  | 'wall'
  | 'militia'
  | 'archer'
  | 'cleric'
  | 'knight'
  | 'goblin'
  | 'orc'
  | 'troll'
  | 'boss';

/**
 * All placeable structure types. Includes unit-spawning buildings (`hut`,
 * `range`, `temple`, `keep`), turrets (`sentry`, `obelisk`, `catapult`,
 * `sorcerer`), resource buildings (`lumber`, `mine_ore`, `mine_gem`, `vault`),
 * logistics (`track`, `mint`), and the passive `wall` barricade.
 */
export type BuildingType =
  | 'wall'
  | 'hut'
  | 'range'
  | 'temple'
  | 'keep'
  | 'sentry'
  | 'obelisk'
  | 'lumber'
  | 'mine_ore'
  | 'mine_gem'
  | 'track'
  | 'mint'
  | 'catapult'
  | 'sorcerer'
  | 'vault';

/**
 * Configuration data for a single building type. Consumed by the engine to
 * determine placement costs, spawned unit types, turret behavior, and UI
 * display metadata.
 */
export interface BuildingConfig {
  /** Gold cost to place this building. */
  cost: number;
  /** Wood cost to place this building (defaults to 0 if omitted). */
  woodCost?: number;
  /** Iron ore cost to place this building. */
  oreCost?: number;
  /** Gem cost to place this building. */
  gemCost?: number;
  /** Meta-currency cost to unlock this building in the tech tree. */
  unlockCost: number;
  /** Whether this occupies a building slot (false for walls and tracks). */
  isBuilding: boolean;
  /** If true, this building fires projectiles at enemies rather than spawning units. */
  isTurret?: boolean;
  /** Emoji icon displayed in the build palette UI. */
  icon: string;
  /** Human-readable display name. */
  name: string;
  /** Short description of the building's strategic role. */
  role: string;
  /** Stat summary string shown in the build tooltip. */
  stats: string;
  /** The unit type this building spawns, or `null` for turrets and passive buildings. */
  unit: UnitType | null;
  /** Seconds between unit spawns (or resource ticks for extractors). */
  spawnTime: number;
  /** Hex color used for the 3D mesh representation. */
  color: number;
  /** Turret attack range in world units. Only meaningful when `isTurret` is true. */
  range?: number;
  /** Turret base damage per projectile. Only meaningful when `isTurret` is true. */
  damage?: number;
  /** Turret attack cooldown in seconds. Only meaningful when `isTurret` is true. */
  atkSpd?: number;
}

/**
 * Master lookup of every building's configuration, keyed by {@link BuildingType}.
 * Used at build-time, upgrade-time, and during the defend-phase simulation loop.
 */
export const BUILDINGS: Record<BuildingType, BuildingConfig> = {
  wall: {
    cost: 0,
    woodCost: 15,
    unlockCost: 0,
    isBuilding: false,
    icon: '🚧',
    name: 'Barricade',
    role: 'Blocks the road to stall advances.',
    stats: 'HP: 600 | DPS: 0',
    unit: 'wall',
    spawnTime: 99,
    color: 0x8b4513,
  },
  hut: {
    cost: 50,
    woodCost: 20,
    unlockCost: 0,
    isBuilding: true,
    icon: '⚔️',
    name: 'Militia Hut',
    role: 'Spawns cheap melee infantry.',
    stats: '40 HP | 10 DMG | 3.5s Spwn',
    unit: 'militia',
    spawnTime: 3.5,
    color: 0x3b82f6,
  },
  lumber: {
    cost: 75,
    woodCost: 0,
    unlockCost: 50,
    isBuilding: true,
    icon: '🪓',
    name: 'Lumber Camp',
    role: 'Harvests wood over time.',
    stats: '+10 Wood / 5s',
    unit: null,
    spawnTime: 5.0,
    color: 0x654321,
  },
  range: {
    cost: 100,
    woodCost: 50,
    unlockCost: 50,
    isBuilding: true,
    icon: '🏹',
    name: 'Archery Range',
    role: 'Spawns long-range archers.',
    stats: '20 HP | 15 DMG | 4.5s Spwn',
    unit: 'archer',
    spawnTime: 4.5,
    color: 0x22c55e,
  },
  temple: {
    cost: 150,
    woodCost: 50,
    unlockCost: 150,
    isBuilding: true,
    icon: '✨',
    name: 'Cleric Temple',
    role: 'Spawns healers to mend allies.',
    stats: '30 HP | 20 HEAL | 6.0s Spwn',
    unit: 'cleric',
    spawnTime: 6.0,
    color: 0x14b8a6,
  },
  keep: {
    cost: 200,
    woodCost: 100,
    unlockCost: 300,
    isBuilding: true,
    icon: '🛡️',
    name: 'Knight Keep',
    role: 'Spawns heavy tanks for the frontline.',
    stats: '150 HP | 25 DMG | 8.0s Spwn',
    unit: 'knight',
    spawnTime: 8.0,
    color: 0x9ca3af,
  },
  sentry: {
    cost: 0,
    woodCost: 100,
    unlockCost: 100,
    isBuilding: true,
    isTurret: true,
    icon: '🏹',
    name: 'Sentry Post',
    role: 'Fires fast arrows directly.',
    stats: '15 DMG | 1.0s ATK | 20 RNG',
    unit: null,
    spawnTime: 0,
    color: 0xaaaaaa,
    range: 20,
    damage: 15,
    atkSpd: 1.0,
  },
  obelisk: {
    cost: 150,
    woodCost: 50,
    unlockCost: 200,
    isBuilding: true,
    isTurret: true,
    icon: '🔮',
    name: 'Arcane Obelisk',
    role: 'Fires heavy magic beams.',
    stats: '40 DMG | 2.5s ATK | 25 RNG',
    unit: null,
    spawnTime: 0,
    color: 0x9932cc,
    range: 25,
    damage: 40,
    atkSpd: 2.5,
  },
  mine_ore: {
    cost: 100,
    woodCost: 50,
    unlockCost: 100,
    isBuilding: true,
    icon: '⛏️',
    name: 'Ore Mine',
    role: 'Harvests iron ore.',
    stats: '+1 Ore / 5s',
    unit: null,
    spawnTime: 5.0,
    color: 0x475569,
  },
  mine_gem: {
    cost: 200,
    woodCost: 100,
    unlockCost: 250,
    isBuilding: true,
    icon: '💎',
    name: 'Gem Mine',
    role: 'Extracts precious gems.',
    stats: '+1 Gem / 10s',
    unit: null,
    spawnTime: 10.0,
    color: 0x06b6d4,
  },
  track: {
    cost: 5,
    woodCost: 5,
    unlockCost: 0,
    isBuilding: false,
    icon: '🛤️',
    name: 'Minecart Track',
    role: 'Transports mined resources to sinks.',
    stats: 'Logistics',
    unit: null,
    spawnTime: 0,
    color: 0x854d0e,
  },
  mint: {
    cost: 150,
    woodCost: 100,
    oreCost: 10,
    unlockCost: 200,
    isBuilding: true,
    icon: '🪙',
    name: 'Royal Mint',
    role: 'Converts Ore into Gold.',
    stats: '1 Ore -> 15 Gold',
    unit: null,
    spawnTime: 0,
    color: 0xeab308,
  },
  catapult: {
    cost: 200,
    woodCost: 150,
    unlockCost: 300,
    isBuilding: true,
    isTurret: true,
    icon: '🪨',
    name: 'Catapult',
    role: 'Fires explosive area-of-effect boulders.',
    stats: '80 DMG | 4.0s ATK | 30 RNG',
    unit: null,
    spawnTime: 0,
    color: 0x8b4513,
    range: 30,
    damage: 80,
    atkSpd: 4.0,
  },
  sorcerer: {
    cost: 150,
    woodCost: 50,
    gemCost: 5,
    unlockCost: 250,
    isBuilding: true,
    isTurret: true,
    icon: '🧙',
    name: 'Sorcerer Tower',
    role: 'Slows down enemy movement.',
    stats: '10 DMG | 1.5s ATK | 20 RNG',
    unit: null,
    spawnTime: 0,
    color: 0x3b82f6,
    range: 20,
    damage: 10,
    atkSpd: 1.5,
  },
  vault: {
    cost: 300,
    woodCost: 200,
    unlockCost: 400,
    isBuilding: true,
    icon: '🏦',
    name: 'Gold Vault',
    role: 'Generates passive gold over time.',
    stats: '+10 Gold / 10s',
    unit: null,
    spawnTime: 10.0,
    color: 0xfacc15,
  },
};

/**
 * Base stat block for a unit archetype. Values here are the *unscaled*
 * defaults; the engine applies wave-scaling multipliers and doctrine bonuses
 * at spawn time.
 */
export interface UnitConfig {
  /** Base hit points. */
  hp: number;
  /** Movement speed in world-units per second. */
  speed: number;
  /** Base damage per attack. Negative values indicate healing (e.g. clerics). */
  damage: number;
  /** Attack/heal range in world units. */
  range: number;
  /** Seconds between attacks. */
  atkSpd: number;
  /** Whether the unit fires ranged projectiles rather than melee striking. */
  isRanged: boolean;
  /** Whether the unit heals allies instead of damaging enemies. */
  isHealer: boolean;
  /** Hex color for the 3D mesh representation. */
  color: number;
  /** Visual scale multiplier applied to the unit mesh. */
  scale: number;
  /** Wave-budget cost consumed when the wave spawner selects this unit (enemies only). */
  cost?: number;
  /** Gold rewarded to the player when this enemy unit is killed. */
  reward?: number;
  /** Default affix always applied to this unit type, if any. */
  baseAffix?: EnemyAffix;
}

/**
 * Master lookup of every unit archetype's base stats, keyed by {@link UnitType}.
 * Ally entries (wall, militia, archer, cleric, knight) lack `cost`/`reward`;
 * enemy entries (goblin, orc, troll, boss) include them for the wave-budget
 * and gold-reward systems.
 */
export const UNITS: Record<UnitType, UnitConfig> = {
  wall: {
    hp: 600,
    speed: 0,
    damage: 0,
    range: 0,
    atkSpd: 99,
    isRanged: false,
    isHealer: false,
    color: 0x8b4513,
    scale: 1.2,
  },
  militia: {
    hp: 40,
    speed: 6.0,
    damage: 10,
    range: 2.0,
    atkSpd: 1.0,
    isRanged: false,
    isHealer: false,
    color: 0x3b82f6,
    scale: 0.8,
  },
  archer: {
    hp: 20,
    speed: 5.0,
    damage: 15,
    range: 15.0,
    atkSpd: 1.5,
    isRanged: true,
    isHealer: false,
    color: 0x22c55e,
    scale: 0.75,
  },
  cleric: {
    hp: 30,
    speed: 4.5,
    damage: -20,
    range: 12.0,
    atkSpd: 2.0,
    isRanged: true,
    isHealer: true,
    color: 0x14b8a6,
    scale: 0.8,
  },
  knight: {
    hp: 150,
    speed: 4.0,
    damage: 25,
    range: 2.5,
    atkSpd: 1.5,
    isRanged: false,
    isHealer: false,
    color: 0x9ca3af,
    scale: 1.1,
  },

  goblin: {
    hp: 30,
    speed: 7.0,
    damage: 5,
    range: 2.0,
    atkSpd: 0.8,
    isRanged: false,
    isHealer: false,
    color: 0x4d7c0f,
    scale: 0.7,
    cost: 5,
    reward: 2,
  },
  orc: {
    hp: 80,
    speed: 5.0,
    damage: 15,
    range: 2.5,
    atkSpd: 1.5,
    isRanged: false,
    isHealer: false,
    color: 0x7f1d1d,
    scale: 1.0,
    cost: 12,
    reward: 5,
  },
  troll: {
    hp: 250,
    speed: 3.5,
    damage: 30,
    range: 3.5,
    atkSpd: 2.0,
    isRanged: false,
    isHealer: false,
    color: 0x1e1b4b,
    scale: 1.4,
    cost: 25,
    reward: 10,
  },
  boss: {
    hp: 1200,
    speed: 2.5,
    damage: 50,
    range: 4.0,
    atkSpd: 3.0,
    isRanged: false,
    isHealer: false,
    color: 0x2d0a28,
    scale: 2.2,
    cost: 150,
    reward: 50,
  },
};
