/**
 * @module constants
 *
 * Static type definitions and data dictionaries for the Grailguard tower-defense
 * engine. Defines the full set of unit types, building types, factions, game
 * phases, spells, and enemy affixes, together with their numerical stats used
 * by the simulation in {@link GameEngine}.
 *
 * Building and unit data is sourced from JSON config files in `src/data/` and
 * re-exported here with proper TypeScript types for compile-time safety.
 */

import unitConfigJson from '../data/unitConfig.json';
import buildingConfigJson from '../data/buildingConfig.json';

/**
 * Which side of the conflict an entity belongs to.
 * - `'ally'` -- player-controlled defenders
 * - `'enemy'` -- wave-spawned attackers
 */
export type Faction = 'ally' | 'enemy';

/**
 * The three high-level phases a game session cycles through.
 * - `'build'`     -- player places and upgrades structures
 * - `'defend'`    -- enemies spawn and advance toward the sanctuary
 * - `'game_over'` -- terminal state after victory or defeat
 */
export type GamePhase = 'build' | 'defend' | 'game_over';

/**
 * Identifiers for the castable spells available to the player.
 * Each spell has a faith cost and cooldown managed in {@link GameEngine}.
 */
export type SpellType =
  | 'smite'
  | 'holy_nova'
  | 'zealous_haste'
  | 'earthquake'
  | 'chrono_shift'
  | 'meteor_strike'
  | 'divine_shield';

/**
 * Modifiers that can be applied to enemy units starting at wave 6.
 * - `'armored'`       -- takes 50% reduced non-magic damage
 * - `'swift'`         -- doubled movement speed and halved attack speed
 * - `'regenerating'`  -- passively regenerates HP over time
 * - `'ranged'`        -- gains a 15-range ranged attack
 * - `'vampiric'`      -- heals for 50% of damage dealt
 * - `'explosive'`     -- deals AoE damage to nearby allies on death
 */
export type EnemyAffix = 'armored' | 'swift' | 'regenerating' | 'ranged' | 'vampiric' | 'explosive';

/**
 * All unit archetypes in the game. Ally units (`wall` through `knight`) are
 * spawned by buildings, while enemy units (`goblin` through `boss`) are
 * generated by the wave system.
 */
export type UnitType =
  | 'wall'
  | 'militia'
  | 'archer'
  | 'cleric'
  | 'knight'
  | 'goblin'
  | 'orc'
  | 'troll'
  | 'boss'
  | 'flying'
  | 'shieldBearer'
  | 'summoner';

/**
 * All placeable structure types. Includes unit-spawning buildings (`hut`,
 * `range`, `temple`, `keep`), turrets (`sentry`, `obelisk`, `catapult`,
 * `sorcerer`), resource buildings (`lumber`, `mine_ore`, `mine_gem`, `vault`),
 * logistics (`track`, `mint`), and the passive `wall` barricade.
 */
export type BuildingType =
  | 'wall'
  | 'hut'
  | 'range'
  | 'temple'
  | 'keep'
  | 'sentry'
  | 'obelisk'
  | 'lumber'
  | 'mine_ore'
  | 'mine_gem'
  | 'track'
  | 'mint'
  | 'catapult'
  | 'sorcerer'
  | 'vault';

/**
 * Configuration data for a single building type. Consumed by the engine to
 * determine placement costs, spawned unit types, turret behavior, and UI
 * display metadata.
 */
export interface BuildingConfig {
  /** Gold cost to place this building. */
  cost: number;
  /** Wood cost to place this building (defaults to 0 if omitted). */
  woodCost?: number;
  /** Iron ore cost to place this building. */
  oreCost?: number;
  /** Gem cost to place this building. */
  gemCost?: number;
  /** Meta-currency cost to unlock this building in the tech tree. */
  unlockCost: number;
  /** Whether this occupies a building slot (false for walls and tracks). */
  isBuilding: boolean;
  /** If true, this building fires projectiles at enemies rather than spawning units. */
  isTurret?: boolean;
  /** Emoji icon displayed in the build palette UI. */
  icon: string;
  /** Human-readable display name. */
  name: string;
  /** Short description of the building's strategic role. */
  role: string;
  /** Stat summary string shown in the build tooltip. */
  stats: string;
  /** The unit type this building spawns, or `null` for turrets and passive buildings. */
  unit: UnitType | null;
  /** Seconds between unit spawns (or resource ticks for extractors). */
  spawnTime: number;
  /** Hex color used for the 3D mesh representation. */
  color: number;
  /** Turret attack range in world units. Only meaningful when `isTurret` is true. */
  range?: number;
  /** Turret base damage per projectile. Only meaningful when `isTurret` is true. */
  damage?: number;
  /** Turret attack cooldown in seconds. Only meaningful when `isTurret` is true. */
  atkSpd?: number;
}

/** Converts a hex color string like "0x8b4513" to its numeric equivalent. */
function parseHexColor(colorStr: string): number {
  return Number.parseInt(colorStr.replace('0x', ''), 16);
}

/**
 * Master lookup of every building's configuration, keyed by {@link BuildingType}.
 * Used at build-time, upgrade-time, and during the defend-phase simulation loop.
 *
 * Sourced from `src/data/buildingConfig.json` and re-exported with typed overlays.
 */
export const BUILDINGS: Record<BuildingType, BuildingConfig> = Object.fromEntries(
  Object.entries(buildingConfigJson.buildings).map(([key, raw]) => [
    key,
    {
      ...raw,
      color: parseHexColor(raw.color),
      unit: raw.unit as UnitType | null,
    } as BuildingConfig,
  ]),
) as Record<BuildingType, BuildingConfig>;

/**
 * Base stat block for a unit archetype. Values here are the *unscaled*
 * defaults; the engine applies wave-scaling multipliers and doctrine bonuses
 * at spawn time.
 */
export interface UnitConfig {
  /** Base hit points. */
  hp: number;
  /** Movement speed in world-units per second. */
  speed: number;
  /** Base damage per attack. Negative values indicate healing (e.g. clerics). */
  damage: number;
  /** Attack/heal range in world units. */
  range: number;
  /** Seconds between attacks. */
  atkSpd: number;
  /** Whether the unit fires ranged projectiles rather than melee striking. */
  isRanged: boolean;
  /** Whether the unit heals allies instead of damaging enemies. */
  isHealer: boolean;
  /** Hex color for the 3D mesh representation. */
  color: number;
  /** Visual scale multiplier applied to the unit mesh. */
  scale: number;
  /** Wave-budget cost consumed when the wave spawner selects this unit (enemies only). */
  cost?: number;
  /** Gold rewarded to the player when this enemy unit is killed. */
  reward?: number;
  /** Default affix always applied to this unit type, if any. */
  baseAffix?: EnemyAffix;
}

/**
 * Master lookup of every unit archetype's base stats, keyed by {@link UnitType}.
 * Ally entries (wall, militia, archer, cleric, knight) lack `cost`/`reward`;
 * enemy entries (goblin, orc, troll, boss) include them for the wave-budget
 * and gold-reward systems.
 *
 * Sourced from `src/data/unitConfig.json` and re-exported with typed overlays.
 */
export const UNITS: Record<UnitType, UnitConfig> = Object.fromEntries(
  Object.entries(unitConfigJson.units).map(([key, raw]) => [
    key,
    {
      ...raw,
      color: parseHexColor(raw.color),
    } as UnitConfig,
  ]),
) as Record<UnitType, UnitConfig>;
